### PR TITLE
fix issues of 'voices/filename' typo.

### PR DESCRIPTION
**Pull request by chenakam**

### CODE REVIEW

**Comment by zthxxx** [comment]
i cannot see what’s the word change, could you explain it?

**Comment by zthxxx** [comment]
It looks exactly the same.

image

**Comment by zthxxx** [comment]
@WeiChou @chenakam

**Comment by chenakam** [comment]
I also found this problem, you have to compare them under IDE to see the difference:

image

**Comment by zthxxx** [comment]
@chenakam  but, what's the reason?

**Comment by zthxxx** [comment]
@chenakam merged, but also needs to change names of relevant files

**Comment by chenakam** [comment]
@zthxxx Not needed, it is because the filename of `.mp3` and `voices/filename` are not equivalent, cause some `keywords` can't trigger out sound, so i found this reason, and i have calibrated all the file names of `.mp3`.

**Comment by zthxxx** [comment]
thanks

**Pull request merged**
