### PR TITLE
contributes info should in a separate file, instead of in manifest.json

### PR DESCRIPTION
**Pull request by izhangzhihao**

### CODE REVIEW

**Comment by zthxxx** [comment]
hello @izhangzhihao 

i cannot find where is the docs of the `contributes.json` ?

**Comment by izhangzhihao** [comment]
Just check the build-in voice package: https://github.com/SaekiRaku/vscode-rainbow-fart/blob/master/src/built-in-voice-packages/built-in-voice-chinese/contributes.json

**Comment by izhangzhihao** [comment]
and https://github.com/SaekiRaku/vscode-rainbow-fart/blob/master/src/built-in-voice-packages/built-in-voice-chinese/manifest.json

**Comment by zthxxx** [comment]
image

**Comment by zthxxx** [comment]
@izhangzhihao Thanks~  I understand.

but please follow the [.editorconfig](https://github.com/zthxxx/kugimiya-rainbow-fart/blob/master/.editorconfig) and use 2 spaces for indent style~

**Comment by izhangzhihao** [comment]
Fixed.

**Comment by zthxxx** [comment]
@izhangzhihao  but i get a error when import

`contributes` need in `manifest.json` 

image

**Comment by zthxxx** [comment]
@izhangzhihao  have you try and test when separated `contributes.json` in your local?

**Comment by izhangzhihao** [comment]
interesting... since the build-in packages do not have this property. But I did tried with the IntellJ version.

**Comment by zthxxx** [comment]
due to https://github.com/SaekiRaku/vscode-rainbow-fart/blob/v1.2.0/src/assets.js#L11

**Comment by zthxxx** [comment]
> due to https://github.com/SaekiRaku/vscode-rainbow-fart/blob/v1.2.0/src/assets.js#L11

@izhangzhihao  here is the reason: 

in [`function add()`](https://github.com/SaekiRaku/vscode-rainbow-fart/blob/v1.2.0/src/assets.js#L91-L94) means import needs some required properties,

but in [`function load()`](https://github.com/SaekiRaku/vscode-rainbow-fart/blob/v1.2.0/src/assets.js#L63-L74), it will merge all `*.json` file, so built-in package can split  and run success

**Comment by zthxxx** [comment]
so I'm very sorry and sad that i need revert your pr.  🙏 sorry.

**Comment by izhangzhihao** [comment]
ok

在 2020年6月21日，下午4:25，zthxxx <notifications@github.com> 写道：

﻿

so I'm very sorry and sad that i need revert your pr. 🙏 sorry.

**Comment by zthxxx** [comment]
revert done.

Thanks for your PR~  I'm also using your intellij-rainbow-fart, awesome!

**Comment by zthxxx** [comment]
Already split `contributes` to the separate file [`keywords-voices.yml`](https://github.com/zthxxx/kugimiya-rainbow-fart/commit/1bb64be682b6f85f68fed356c819628760fec1a6#diff-61a617185abd03186b12e5c478a47937), and will be merge into `manifest.json` [when build](https://github.com/zthxxx/kugimiya-rainbow-fart/blob/1bb64be682b6f85f68fed356c819628760fec1a6/gulpfile.js#L26) for compatible import.

ref: https://github.com/zthxxx/kugimiya-rainbow-fart/commit/1bb64be682b6f85f68fed356c819628760fec1a6#diff-61a617185abd03186b12e5c478a47937

**Comment by izhangzhihao** [comment]
So, I had to download the release and unzip it?

The doc is [updated](https://github.com/izhangzhihao/intellij-rainbow-fart/commit/92b60cb74868900d2147593d9234b498e0467f17).

**Comment by zthxxx** [comment]
I just noticed the install example 🌝

**Comment by izhangzhihao** [comment]
And I just wonder why I got so many FileNotFound errors...

**Comment by izhangzhihao** [comment]
And I found your comment.

**Comment by zthxxx** [comment]
🐶

aha, I updated the docs too~

izhangzhihao/intellij-rainbow-fart#30

**Pull request merged**
